version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES:-}
      WEB_USER: ${WEB_USER}
      WEB_PASSWORD: ${WEB_PASSWORD}
      EXTRA_USERS_ENABLED: ${EXTRA_USERS_ENABLED:-false}
      EXTRA_USERS: ${EXTRA_USERS}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./backups:/backups
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:8432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-mydb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network
      - nginx_network
    shm_size: 256mb  # для больших запросов

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    name: nginx-proxy
    external: true